### ISSUE TITLE
API discussion

### ISSUE THREAD

**Issue by Datseris** [JuliaDynamics/SpatioTemporalSystems.jl#1]
@JonasIsensee I've drafted an API at the README.md . Have a look and tell me what you think.

Keep in mind that for this to be long-term useful it should not be **too** specialized on the current state of the project. For example, I have left all arguments about solving the system to be specified by the user, instead of allowing arguments like `Nt, Ttr,` etc. (we anyways use different formalism here: I always use the physical time to evolve for, while you often use number of steps to evolve for directly).

**Comment by JonasIsensee** [comment]
Your API draft looks good.

I only have one concern. I'm not a fan of having to pass an initial condition.
You mention that it might be difficult to implement this in general and I completely agree.
However I believe it would not be a problem to implement the initialization for each model system
independently only taking system-size and a seed.
Not all random field as input produce proper dynamics.. and after all we're not planning to add that many systems either.

We could default to producing an initial condition if none is given.

**Comment by Datseris** [comment]
Sure, this seems okay. But also some further clarification : 

Do you mean that the default initial condition will be random, and thus always changing, or that it will be a fixed one that we know that results in "reasonable" dynamics?

**Comment by JonasIsensee** [comment]
For Barkley we have random initial conditions implemented. For KS we don't. One could always use the same oneand randomly choose (using seed) a transient/throwawayintegration time. (+plus constant to not accidentally get the actual transient in the beginning)

**Comment by Datseris** [comment]
Okay, this is fine then. I'll move on with this suggestion:

> One could always use the same one and randomly choose (using seed) a  ransient/throwawayintegration time

seems to be the safest and smartest approach.
